import { makeStyles, tokens } from "@fluentui/react-components";

export const SIDE_PADDING = "6px";
// Scroll containers reserve a both-edges scrollbar gutter (6px — the
// `::-webkit-scrollbar` width in App.css), so their content sits
// LIST_SIDE_PADDING + SCROLLBAR_GUTTER in from each edge. Non-scrolling areas
// use NONSCROLL_SIDE_PADDING to land their pills on that same line.
const SCROLLBAR_GUTTER = "6px";
const LIST_SIDE_PADDING = "2px";
const NONSCROLL_SIDE_PADDING = `calc(${LIST_SIDE_PADDING} + ${SCROLLBAR_GUTTER})`;
// A small extra inset on the editor-facing right edge so the list (pills,
// trailing timestamps/badges/more-buttons) reads a touch further from the
// editor pane. Applied as container padding on `.sidebar` so every child —
// scrolling lists, the fixed new-note area, and the footer — shifts left
// together, keeping their existing left alignment and internal gutter math
// intact. The absolutely-positioned top buttons in App.styles.ts are nudged
// by the same amount to stay level with the pills.
const LIST_RIGHT_GAP = "4px";

export const useStyles = makeStyles({
  sidebar: {
    display: "flex",
    flexDirection: "column",
    width: "var(--shell-sidebar-width)",
    height: "100%",
    backgroundColor: "transparent",
    flexShrink: 0,
    userSelect: "none",
    // border-box keeps the sidebar's overall width pinned to the slot while
    // this padding pushes all content in from the editor-facing edge.
    paddingRight: LIST_RIGHT_GAP,
    "--update-dot-color": tokens.colorBrandBackground,
  },
  sidebarFixed: {
    flexShrink: 0,
    paddingTop: "55px",
    // No scrollbar gutter here, so pad by the full non-scroll inset to align
    // the new-note button with the note rows below.
    paddingLeft: NONSCROLL_SIDE_PADDING,
    paddingRight: NONSCROLL_SIDE_PADDING,
  },
  body: {
    width: "50%",
    height: "100%",
    flexShrink: 0,
    overflowX: "hidden",
    overflowY: "auto",
    scrollbarGutter: "stable both-edges",
    paddingLeft: LIST_SIDE_PADDING,
    paddingRight: LIST_SIDE_PADDING,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    "--sidebar-mask-top": "0px",
    "--sidebar-mask-bottom": "0px",
    maskImage: "linear-gradient(to bottom, transparent, black var(--sidebar-mask-top), black calc(100% - var(--sidebar-mask-bottom)), transparent)",
    transitionProperty: "--sidebar-mask-top, --sidebar-mask-bottom",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
    "&[data-scroll-top='false']": {
      "--sidebar-mask-top": "24px",
    },
    "&[data-scroll-bottom='false']": {
      "--sidebar-mask-bottom": "24px",
    },
  },
  bodyArea: {
    flex: 1,
    minHeight: 0,
    overflow: "hidden",
  },
  viewTrack: {
    display: "flex",
    width: "200%",
    height: "100%",
    transform: "translateX(0)",
    transitionProperty: "transform",
    transitionDuration: "0.24s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  viewTrackShifted: {
    transform: "translateX(-50%)",
  },
  allNotesPane: {
    width: "50%",
    height: "100%",
    flexShrink: 0,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
  },
  allNotesHeader: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    marginBottom: "2px",
    // Side margins inset the header into a contained pill aligned with the
    // note rows. The header has no scrollbar gutter of its own, so it uses the
    // full non-scroll inset. paddingLeft matches `docItem`'s row padding so the
    // chevron and label line up with the list.
    marginLeft: NONSCROLL_SIDE_PADDING,
    marginRight: NONSCROLL_SIDE_PADDING,
    maxWidth: "none",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  allNotesHeaderLabel: {
    flex: 1,
    textAlign: "left",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  // Optical correction: the back chevron's glyph sits inset within its slot,
  // so nudge it 2px left to read level with the note list's document icons.
  allNotesHeaderIcon: {
    transform: "translateX(-2px)",
  },
  allNotesScroll: {
    flex: 1,
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    scrollbarGutter: "stable both-edges",
    paddingLeft: LIST_SIDE_PADDING,
    paddingRight: LIST_SIDE_PADDING,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    "--sidebar-mask-top": "0px",
    "--sidebar-mask-bottom": "0px",
    maskImage: "linear-gradient(to bottom, transparent, black var(--sidebar-mask-top), black calc(100% - var(--sidebar-mask-bottom)), transparent)",
    transitionProperty: "--sidebar-mask-top, --sidebar-mask-bottom",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
    "&[data-scroll-top='false']": {
      "--sidebar-mask-top": "24px",
    },
    "&[data-scroll-bottom='false']": {
      "--sidebar-mask-bottom": "24px",
    },
  },
  allNotesEntry: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    fontWeight: 500,
    marginBottom: "12px",
    flexShrink: 0,
  },
  allNotesEntryName: {
    flex: 1,
    textAlign: "left",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  allNotesEntryCount: {
    fontSize: "11px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground3,
    opacity: 0.8,
    flexShrink: 0,
  },
  allNotesEntryChevron: {
    display: "flex",
    alignItems: "center",
    color: tokens.colorNeutralForeground3,
    flexShrink: 0,
    // Optical alignment: nudge the chevron down 0.5px to sit level with the label.
    transform: "translateY(0.5px)",
  },
  docItemWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    // Hover-driven trailing-slot hide and more-button reveal are done via CSS
    // :hover (not React state) so mouse enter/leave reacts immediately without
    // re-rendering the whole sidebar — keeps the unhover transition snappy.
    "&:hover [data-doc-trailing]": {
      opacity: 0,
      pointerEvents: "none",
    },
    "&:hover [data-more-btn]": {
      opacity: 1,
      pointerEvents: "auto",
    },
  },
  docItemNew: {
    animationName: "docSlideIn",
    animationDuration: "0.3s",
    animationTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
    animationFillMode: "backwards",
  },
  docItemSlideUp: {
    animationName: "docSlideUp",
    animationDuration: "0.2s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  docItemExit: {
    animationName: "docSlideOut",
    animationDuration: "0.25s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    animationFillMode: "forwards",
    pointerEvents: "none" as const,
    overflow: "hidden",
  },
  // Per-group note container. The whole block of a group's notes slides as a
  // single unit via the CSS Grid `1fr` ↔ `0fr` row trick (same technique as
  // `groupsSection` below) — one smooth layout animation instead of one
  // max-height animation per note. The wrapper is always mounted per group so
  // the transition fires reliably on the `groupNotesSlideCollapsed` class flip.
  groupNotesSlide: {
    display: "grid",
    gridTemplateRows: "1fr",
    marginTop: "0px",
    transitionProperty: "grid-template-rows, opacity, margin-top",
    transitionDuration: "0.28s",
    transitionTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
  },
  groupNotesSlideCollapsed: {
    gridTemplateRows: "0fr",
    opacity: 0,
    // Cancels the parent's `gap: 2px` so a collapsed (0-height) wrapper does
    // not leave a doubled 4px gap between adjacent group headers.
    marginTop: "-2px",
  },
  groupNotesSlideInner: {
    overflow: "hidden",
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  groupCollapseOut: {
    animationName: "groupCollapseOut",
    animationDuration: "0.28s",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    animationFillMode: "forwards",
    overflow: "hidden",
    pointerEvents: "none",
  },
  searchResultFadeIn: {
    animationName: "searchResultFadeIn",
    animationDuration: "0.25s",
    animationTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
    animationFillMode: "backwards",
  },
  searchResultContent: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    gap: "2px",
    paddingTop: "4px",
    paddingBottom: "4px",
  },
  searchSnippet: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: "16px",
  },
  snippetHighlight: {
    backgroundColor: "transparent",
    color: tokens.colorBrandForeground1,
    fontWeight: 600,
  },
  docItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  docItemActive: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: "var(--ui-active-bg)",
    fontWeight: 500,
  },
  docItemIndented: {
    paddingLeft: "20px",
  },
  docItemIcon: {
    display: "flex",
    // Pin the icon to the resting foreground colour so it does not inherit
    // the subtle Button's brand-tinted hover colour (colorNeutralForeground2-
    // BrandHover) — a hovered uncoloured note's icon turning blue is
    // indistinguishable from the blue colour label. A note that has a colour
    // label overrides this inline.
    color: tokens.colorNeutralForeground2,
  },
  // Select mode: the active-note fill moves from the note button onto the
  // wrapper so it also wraps the checkbox.
  docItemWrapperActive: {
    backgroundColor: "var(--ui-active-bg)",
    borderRadius: "6px",
  },
  // Select-mode hover counterpart of docItemWrapperActive. Uses CSS :hover on
  // the wrapper so the paint fires immediately on mouse entry (including the
  // checkbox area) without a React-state-driven re-render.
  docItemWrapperHoverable: {
    ":hover": {
      backgroundColor: "var(--ui-hover-bg)",
      borderRadius: "6px",
    },
  },
  // In select mode the wrapper paints the row-level hover/active fill so it
  // can include the checkbox. Suppress the inner Fluent Button's hover/active
  // fill (defined globally in App.css with !important) so the two layers don't
  // stack and tint the Button area darker than the checkbox area.
  docItemSelectRow: {
    "& .fui-Button:hover, & .fui-Button:active": {
      backgroundColor: "transparent !important",
    },
  },
  // Clears the note button's own active background in select mode — the fill
  // now lives on the wrapper, and --ui-active-bg is translucent so keeping
  // both would tint the note portion darker than the checkbox portion.
  docItemActiveBgClear: {
    backgroundColor: "transparent",
  },
  // Tightens the checkbox-to-icon gap in select mode (docItem's default
  // paddingLeft is 8px).
  docItemSelectGap: {
    paddingLeft: "4px",
  },
  newDocItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    fontWeight: 500,
    marginBottom: "4px",
    "& .new-doc-shortcut": {
      marginLeft: "auto",
      fontSize: "11px",
      color: tokens.colorNeutralForeground3,
      opacity: 0,
      flexShrink: 0,
      whiteSpace: "nowrap",
      fontWeight: 400,
      transitionProperty: "opacity",
      transitionDuration: "0.15s",
    },
    ":hover .new-doc-shortcut": {
      opacity: 0.7,
    },
  },
  filterChip: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    margin: "0 0 4px",
    padding: "0 4px",
    fontSize: "12px",
    color: tokens.colorNeutralForeground2,
    minHeight: "26px",
  },
  filterChipDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    flexShrink: 0,
  },
  filterChipText: {
    whiteSpace: "nowrap",
  },
  filterChipClear: {
    minWidth: "20px",
    width: "20px",
    height: "20px",
    padding: 0,
    borderRadius: "4px",
    flexShrink: 0,
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 500,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: tokens.colorNeutralForeground4,
    opacity: 0.85,
    paddingLeft: "10px",
    paddingBottom: "4px",
  },
  groupsSection: {
    display: "grid",
    gridTemplateRows: "1fr",
    transitionProperty: "grid-template-rows, opacity, margin-bottom",
    transitionDuration: "0.25s",
    transitionTimingFunction: "ease",
    marginBottom: "12px",
  },
  groupsSectionHidden: {
    gridTemplateRows: "0fr",
    opacity: 0,
    marginBottom: "0px",
  },
  groupsSectionInner: {
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  // Mirror `groupsSectionInner` so the label→list gap and row spacing match
  // the groups section.
  notesSection: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  docName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    textAlign: "left",
  },
  renameInput: {
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "20px",
    padding: "2px 6px",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    minWidth: 0,
    flex: 1,
    borderRadius: "3px",
    marginLeft: "-6px",
  },
  moreBtn: {
    position: "absolute",
    right: "4px",
    top: "50%",
    transform: "translateY(-50%)",
    border: "none",
    borderRadius: "4px",
    minWidth: "auto",
    width: "24px",
    height: "24px",
    padding: "0",
    opacity: 0,
    pointerEvents: "none",
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  moreBtnVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
  moreBtnActive: {
    opacity: 1,
    pointerEvents: "auto",
    backgroundColor: "var(--ui-active-bg)",
  },
  docTrailing: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  docTrailingHidden: {
    opacity: 0,
    pointerEvents: "none",
  },
  docTimestamp: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground3,
    opacity: 0.7,
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  dirtyDot: {
    fontSize: "8px",
    color: tokens.colorNeutralForeground3,
    opacity: 0.7,
    flexShrink: 0,
    lineHeight: 1,
  },
  empty: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.6",
    paddingTop: "10px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  footer: {
    flexShrink: 0,
    // No scrollbar gutter here, so pad by the full non-scroll inset to align
    // the settings button with the new-note button and note rows.
    paddingLeft: NONSCROLL_SIDE_PADDING,
    paddingRight: NONSCROLL_SIDE_PADDING,
    paddingBottom: SIDE_PADDING,
  },
  settingsBtn: {
    width: "100%",
    justifyContent: "flex-start",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "36px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  // Delete-undo toast, parked just above the settings button.
  undoToast: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: "4px",
    marginLeft: `calc(${NONSCROLL_SIDE_PADDING} + 6px)`,
    marginRight: `calc(${NONSCROLL_SIDE_PADDING} + 6px)`,
    marginBottom: "4px",
    paddingTop: "7px",
    paddingBottom: "7px",
    paddingLeft: "10px",
    paddingRight: "4px",
    borderRadius: "8px",
    backgroundColor: tokens.colorNeutralBackground1,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow8,
    fontSize: "12px",
    animationName: {
      from: { opacity: 0, transform: "translateY(6px)" },
      to: { opacity: 1, transform: "translateY(0)" },
    },
    animationDuration: "0.15s",
    animationTimingFunction: "ease-out",
  },
  undoToastText: {
    flexGrow: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: tokens.colorNeutralForeground2,
  },
  undoToastBtn: {
    flexShrink: 0,
    fontSize: "12px",
    fontWeight: 600,
    minHeight: "24px",
    paddingLeft: "8px",
    paddingRight: "8px",
    color: tokens.colorBrandForeground1,
  },
  undoToastDismiss: {
    flexShrink: 0,
    minWidth: "24px",
    minHeight: "24px",
    paddingLeft: "2px",
    paddingRight: "2px",
  },
  updateDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "var(--update-dot-color)",
    marginLeft: "auto",
    marginRight: "6px",
    flexShrink: 0,
    boxShadow: "0 0 4px var(--update-dot-color), 0 0 7px var(--update-dot-color)",
  },
  contextMenu: {
    position: "fixed",
    zIndex: 1000,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "4px",
    minWidth: "210px",
  },
  contextMenuItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "4px",
    fontSize: "13px",
    gap: "8px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "12px",
  },
  contextMenuDanger: {
    color: tokens.colorPaletteRedForeground1,
  },
  shortcutHint: {
    marginLeft: "auto",
    paddingLeft: "24px",
    fontSize: "12px",
    opacity: 0.45,
    whiteSpace: "nowrap" as const,
  },
  submenuParent: {
    position: "relative",
  },
  submenuArrow: {
    marginLeft: "auto",
    fontSize: "10px",
    color: tokens.colorNeutralForeground3,
  },
  submenu: {
    position: "fixed",
    zIndex: 1001,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "4px",
    minWidth: "140px",
  },
  colorRow: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    flexWrap: "wrap",
    padding: "6px 8px",
  },
  colorSwatch: {
    width: "18px",
    height: "18px",
    flexShrink: 0,
    padding: 0,
    borderRadius: "50%",
    // Subtle ring so light swatches stay visible on the menu background.
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    outline: "none",
    transitionProperty: "transform",
    transitionDuration: "0.1s",
    ":hover": {
      transform: "scale(1.18)",
    },
  },
  colorSwatchSelected: {
    outline: `2px solid ${tokens.colorNeutralForeground1}`,
    outlineOffset: "1px",
  },
  filterPopover: {
    position: "fixed",
    zIndex: 1000,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "4px",
    display: "flex",
    flexDirection: "column",
  },
  confirmOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 1002,
  },
  confirmPopover: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "10px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "16px",
    width: "240px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    zIndex: 1003,
  },
  confirmMessage: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground1,
    lineHeight: "1.45",
    textAlign: "center" as const,
  },
  confirmActions: {
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
  },
  searchBoxWrapper: {
    flexShrink: 0,
    overflow: "hidden",
    maxHeight: "0px",
    opacity: 0,
    transitionProperty: "max-height, opacity, margin-bottom",
    transitionDuration: "0.2s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    marginBottom: "0px",
  },
  searchBoxWrapperOpen: {
    maxHeight: "40px",
    opacity: 1,
    marginBottom: "4px",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    paddingLeft: "6px",
    paddingRight: "2px",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "28px",
    padding: "0 8px 0 14px",
    backgroundColor: "var(--sidebar-search-bg, rgba(0, 0, 0, 0.06))",
    color: tokens.colorNeutralForeground1,
    borderRadius: "6px",
    minWidth: 0,
    "::placeholder": {
      color: tokens.colorNeutralForeground4,
    },
  },
  searchCloseBtn: {
    border: "none",
    borderRadius: "4px",
    minWidth: "auto",
    width: "24px",
    height: "24px",
    padding: "0",
    flexShrink: 0,
  },
  groupHeader: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    cursor: "pointer",
  },
  // Stand-in selection cue for the active note when its group is
  // collapsed: the note row itself isn't rendered, so the header adopts
  // the `docItemActive` background and stroke so it's still obvious where
  // the open note lives. Re-expanding restores the note-row cue and this
  // class falls off.
  groupHeaderActive: {
    backgroundColor: "var(--ui-active-bg)",
    fontWeight: 500,
  },
  groupChevron: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "16px",
    height: "16px",
    flexShrink: 0,
    color: tokens.colorNeutralForeground3,
    transitionProperty: "transform",
    transitionDuration: "0.15s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  groupChevronExpanded: {
    transform: "rotate(90deg)",
  },
  groupName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    textAlign: "left",
  },
  groupCount: {
    fontSize: "11px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground3,
    opacity: 0.8,
    flexShrink: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  groupNameInput: {
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "20px",
    padding: "2px 6px",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    minWidth: 0,
    flex: 1,
    borderRadius: "3px",
  },
  selectCheckbox: {
    width: 0,
    height: "16px",
    flexShrink: 0,
    cursor: "pointer",
    borderRadius: "3px",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens.colorNeutralForeground1,
    opacity: 0,
    transitionProperty: "width, opacity, background-color, margin",
    transitionDuration: "0.15s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    padding: 0,
    marginLeft: 0,
    overflow: "hidden",
    color: tokens.colorNeutralForeground1,
    fontSize: "14px",
    lineHeight: 1,
    pointerEvents: "none",
  },
  selectCheckboxVisible: {
    width: "16px",
    opacity: 0.15,
    marginLeft: "4px",
    pointerEvents: "auto",
  },
  selectCheckboxChecked: {
    opacity: 1,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralBackground1,
  },
  selectToolbar: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    paddingLeft: SIDE_PADDING,
    paddingRight: SIDE_PADDING,
    paddingBottom: "4px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: "4px",
    flexWrap: "wrap",
  },
  selectInfo: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    paddingLeft: "4px",
    paddingRight: "4px",
    flexShrink: 0,
  },
  selectActionBtn: {
    border: "none",
    borderRadius: "6px",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    flexShrink: 0,
  },
});
