import { makeStyles, tokens } from "@fluentui/react-components";

export const SIDE_PADDING = "6px";
const LIST_SIDE_PADDING = "8px";

export const useStyles = makeStyles({
  sidebar: {
    display: "flex",
    flexDirection: "column",
    width: "var(--shell-sidebar-width)",
    height: "100%",
    backgroundColor: "transparent",
    flexShrink: 0,
    userSelect: "none",
    "--update-dot-color": tokens.colorBrandBackground,
  },
  sidebarFixed: {
    flexShrink: 0,
    paddingTop: "55px",
    paddingLeft: SIDE_PADDING,
    paddingRight: SIDE_PADDING,
  },
  body: {
    flex: 1,
    overflowX: "hidden",
    overflowY: "auto",
    scrollbarGutter: "stable",
    paddingLeft: LIST_SIDE_PADDING,
    paddingRight: LIST_SIDE_PADDING,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    "--sidebar-mask-top": "0px",
    "--sidebar-mask-bottom": "0px",
    maskImage: "linear-gradient(to bottom, transparent, black var(--sidebar-mask-top), black calc(100% - var(--sidebar-mask-bottom)), transparent)",
    transitionProperty: "--sidebar-mask-top, --sidebar-mask-bottom",
    transitionDuration: "0.3s",
    transitionTimingFunction: "ease",
    "&[data-scroll-top='false']": {
      "--sidebar-mask-top": "24px",
    },
    "&[data-scroll-bottom='false']": {
      "--sidebar-mask-bottom": "24px",
    },
  },
  docItemWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
  },
  docItemNew: {
    animationName: "docSlideIn",
    animationDuration: "0.3s",
    animationTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
    animationFillMode: "backwards",
  },
  docItemSlideUp: {
    animationName: "docSlideUp",
    animationDuration: "0.2s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  docItemExit: {
    animationName: "docSlideOut",
    animationDuration: "0.25s",
    animationTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    animationFillMode: "forwards",
    pointerEvents: "none" as const,
    overflow: "hidden",
  },
  groupChildExpand: {
    animationName: "groupChildExpand",
    animationDuration: "0.28s",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    animationFillMode: "backwards",
  },
  groupCollapseOut: {
    animationName: "groupCollapseOut",
    animationDuration: "0.28s",
    animationTimingFunction: "cubic-bezier(0.22, 1, 0.36, 1)",
    animationFillMode: "forwards",
    overflow: "hidden",
    pointerEvents: "none",
  },
  searchResultFadeIn: {
    animationName: "searchResultFadeIn",
    animationDuration: "0.25s",
    animationTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
    animationFillMode: "backwards",
  },
  searchResultContent: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    gap: "2px",
    paddingTop: "4px",
    paddingBottom: "4px",
  },
  searchSnippet: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    lineHeight: "16px",
  },
  snippetHighlight: {
    backgroundColor: "transparent",
    color: tokens.colorBrandForeground1,
    fontWeight: 600,
  },
  docItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  docItemActive: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    backgroundColor: "var(--ui-active-bg)",
    fontWeight: 500,
  },
  docItemIndented: {
    paddingLeft: "20px",
  },
  newDocItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "8px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "8px",
    fontWeight: 500,
    marginBottom: "8px",
    "& .new-doc-shortcut": {
      marginLeft: "auto",
      fontSize: "11px",
      color: tokens.colorNeutralForeground3,
      opacity: 0,
      flexShrink: 0,
      whiteSpace: "nowrap",
      fontWeight: 400,
      transitionProperty: "opacity",
      transitionDuration: "0.15s",
    },
    ":hover .new-doc-shortcut": {
      opacity: 0.7,
    },
  },
  sectionLabel: {
    fontSize: "11px",
    fontWeight: 500,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: tokens.colorNeutralForeground4,
    opacity: 0.85,
    paddingLeft: "10px",
    paddingBottom: "4px",
  },
  groupsSection: {
    display: "grid",
    gridTemplateRows: "1fr",
    transitionProperty: "grid-template-rows, opacity, margin-bottom",
    transitionDuration: "0.25s",
    transitionTimingFunction: "ease",
    marginBottom: "8px",
  },
  groupsSectionHidden: {
    gridTemplateRows: "0fr",
    opacity: 0,
    marginBottom: "0px",
  },
  groupsSectionInner: {
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  docName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    textAlign: "left",
  },
  renameInput: {
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "20px",
    padding: "2px 6px",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    minWidth: 0,
    flex: 1,
    borderRadius: "3px",
    marginLeft: "-6px",
  },
  moreBtn: {
    position: "absolute",
    right: "4px",
    top: "50%",
    transform: "translateY(-50%)",
    border: "none",
    borderRadius: "4px",
    minWidth: "auto",
    width: "24px",
    height: "24px",
    padding: "0",
    opacity: 0,
    pointerEvents: "none",
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  moreBtnVisible: {
    opacity: 1,
    pointerEvents: "auto",
  },
  moreBtnActive: {
    opacity: 1,
    pointerEvents: "auto",
    backgroundColor: "var(--ui-active-bg)",
  },
  docTrailing: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    flexShrink: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  docTrailingHidden: {
    opacity: 0,
    pointerEvents: "none",
  },
  docTimestamp: {
    fontSize: "11px",
    color: tokens.colorNeutralForeground3,
    opacity: 0.7,
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  dirtyDot: {
    fontSize: "8px",
    color: tokens.colorNeutralForeground3,
    opacity: 0.7,
    flexShrink: 0,
    lineHeight: 1,
  },
  empty: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.6",
    paddingTop: "10px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  footer: {
    flexShrink: 0,
    paddingLeft: SIDE_PADDING,
    paddingRight: SIDE_PADDING,
    paddingBottom: SIDE_PADDING,
  },
  settingsBtn: {
    width: "100%",
    justifyContent: "flex-start",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "5px",
    minHeight: "36px",
    paddingLeft: "8px",
    paddingRight: "8px",
  },
  updateDot: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "var(--update-dot-color)",
    marginLeft: "auto",
    marginRight: "6px",
    flexShrink: 0,
    boxShadow: "0 0 4px var(--update-dot-color), 0 0 7px var(--update-dot-color)",
  },
  contextMenu: {
    position: "fixed",
    zIndex: 1000,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "4px",
    minWidth: "210px",
  },
  contextMenuItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "4px",
    fontSize: "13px",
    gap: "8px",
    minHeight: "32px",
    paddingLeft: "8px",
    paddingRight: "12px",
  },
  contextMenuDanger: {
    color: tokens.colorPaletteRedForeground1,
  },
  shortcutHint: {
    marginLeft: "auto",
    paddingLeft: "24px",
    fontSize: "12px",
    opacity: 0.45,
    whiteSpace: "nowrap" as const,
  },
  submenuParent: {
    position: "relative",
  },
  submenuArrow: {
    marginLeft: "auto",
    fontSize: "10px",
    color: tokens.colorNeutralForeground3,
  },
  submenu: {
    position: "fixed",
    zIndex: 1001,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "8px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "4px",
    minWidth: "140px",
  },
  confirmOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 1002,
  },
  confirmPopover: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: "10px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    boxShadow: tokens.shadow16,
    padding: "16px",
    width: "240px",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    zIndex: 1003,
  },
  confirmMessage: {
    fontSize: "13px",
    color: tokens.colorNeutralForeground1,
    lineHeight: "1.45",
    textAlign: "center" as const,
  },
  confirmActions: {
    display: "flex",
    gap: "8px",
    justifyContent: "flex-end",
  },
  searchBoxWrapper: {
    flexShrink: 0,
    overflow: "hidden",
    maxHeight: "0px",
    opacity: 0,
    transitionProperty: "max-height, opacity, margin-bottom",
    transitionDuration: "0.2s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    marginBottom: "0px",
  },
  searchBoxWrapperOpen: {
    maxHeight: "40px",
    opacity: 1,
    marginBottom: "4px",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
    paddingLeft: "6px",
    paddingRight: "2px",
  },
  searchInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "28px",
    padding: "0 8px 0 14px",
    backgroundColor: "var(--sidebar-search-bg, rgba(0, 0, 0, 0.06))",
    color: tokens.colorNeutralForeground1,
    borderRadius: "6px",
    minWidth: 0,
    "::placeholder": {
      color: tokens.colorNeutralForeground4,
    },
  },
  searchCloseBtn: {
    border: "none",
    borderRadius: "4px",
    minWidth: "auto",
    width: "24px",
    height: "24px",
    padding: "0",
    flexShrink: 0,
  },
  /* ─── Group styles ─── */
  groupHeader: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "flex-start",
    textAlign: "left",
    border: "none",
    borderRadius: "6px",
    fontSize: "13px",
    gap: "4px",
    minHeight: "32px",
    paddingLeft: "6px",
    paddingRight: "8px",
    cursor: "pointer",
  },
  // Stand-in selection cue for the active note when its group is
  // collapsed: the note row itself isn't rendered, so the header adopts
  // the `docItemActive` background and stroke so it's still obvious where
  // the open note lives. Re-expanding restores the note-row cue and this
  // class falls off.
  groupHeaderActive: {
    backgroundColor: "var(--ui-active-bg)",
    fontWeight: 500,
  },
  groupChevron: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "16px",
    height: "16px",
    flexShrink: 0,
    color: tokens.colorNeutralForeground3,
    transitionProperty: "transform",
    transitionDuration: "0.15s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  groupChevronExpanded: {
    transform: "rotate(90deg)",
  },
  groupName: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
    textAlign: "left",
  },
  groupCount: {
    fontSize: "11px",
    fontWeight: 500,
    color: tokens.colorNeutralForeground3,
    opacity: 0.8,
    flexShrink: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.1s",
  },
  groupNameInput: {
    border: "none",
    outline: "none",
    fontSize: "13px",
    fontFamily: "inherit",
    lineHeight: "20px",
    padding: "2px 6px",
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground1,
    minWidth: 0,
    flex: 1,
    borderRadius: "3px",
  },
  /* ─── Multi-select ─── */
  selectCheckbox: {
    width: 0,
    height: "16px",
    flexShrink: 0,
    cursor: "pointer",
    borderRadius: "3px",
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens.colorNeutralForeground1,
    opacity: 0,
    transitionProperty: "width, opacity, background-color, margin",
    transitionDuration: "0.15s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    padding: 0,
    marginLeft: 0,
    overflow: "hidden",
    color: tokens.colorNeutralForeground1,
    fontSize: "14px",
    lineHeight: 1,
    pointerEvents: "none",
  },
  selectCheckboxVisible: {
    width: "16px",
    opacity: 0.15,
    marginLeft: "4px",
    pointerEvents: "auto",
  },
  selectCheckboxChecked: {
    opacity: 1,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralBackground1,
  },
  selectToolbar: {
    display: "flex",
    alignItems: "center",
    gap: "2px",
    paddingLeft: SIDE_PADDING,
    paddingRight: SIDE_PADDING,
    paddingBottom: "4px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    paddingTop: "4px",
    flexWrap: "wrap",
  },
  selectInfo: {
    fontSize: "12px",
    color: tokens.colorNeutralForeground3,
    paddingLeft: "4px",
    paddingRight: "4px",
    flexShrink: 0,
  },
  selectActionBtn: {
    border: "none",
    borderRadius: "6px",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    flexShrink: 0,
  },
});
