import { makeStyles, tokens } from "@fluentui/react-components";
import {
  MOTION_DURATION_BASE,
  MOTION_DURATION_FAST,
  MOTION_DURATION_MEDIUM,
  MOTION_DURATION_SLOW,
  MOTION_DURATION_SLOWER,
  MOTION_DURATION_SLOWEST,
  pressableButton,
} from "./styles/interactions";

export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    color: tokens.colorNeutralForeground1,
    position: "relative",
  },
  micaOverlay: {
    position: "absolute",
    inset: "0",
    pointerEvents: "none",
    zIndex: 1,
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: MOTION_DURATION_SLOWEST,
    transitionTimingFunction: "ease",
  },
  micaOverlayActive: {
    opacity: 1,
  },
  body: {
    flex: "1",
    display: "flex",
    position: "relative",
    overflow: "hidden",
    zIndex: 2,
  },
  sidebarSlot: {
    position: "relative",
    width: 0,
    flexShrink: 0,
    overflow: "hidden",
  },
  sidebarSlotAnimated: {
    transitionProperty: "width",
    transitionDuration: MOTION_DURATION_SLOWER,
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarSlotOpen: {
    width: "var(--shell-sidebar-width)",
    overflow: "visible",
  },
  sidebarResizer: {
    position: "absolute",
    right: "-4px",
    top: 0,
    bottom: 0,
    width: "8px",
    cursor: "ew-resize",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "::after": {
      content: '""',
      width: "4px",
      height: "56px",
      borderRadius: "4px",
      backgroundColor: tokens.colorBrandStroke1,
      opacity: 0,
      transitionProperty: "opacity",
      transitionDuration: MOTION_DURATION_BASE,
    },
    ":hover::after": {
      opacity: 1,
      transitionDelay: MOTION_DURATION_SLOWER,
    },
  },
  sidebarResizing: {
    cursor: "ew-resize",
    "::after": {
      opacity: "1 !important",
    },
  },
  sidebarToggle: {
    position: "absolute",
    top: "13px",
    // 9px + 3px wrapper padding + the 4px icon inset within the 28px button
    // lands the toggle icon at x=16px, level with the sidebar content icons
    // (new-note button, note rows).
    left: "9px",
    zIndex: 20,
    display: "inline-flex",
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "8px",
    padding: "3px",
    pointerEvents: "none",
  },
  sidebarToggleBtn: {
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    pointerEvents: "auto",
    ...pressableButton,
  },
  sidebarSearchBtn: {
    position: "absolute",
    top: "16px",
    // Top-button row right offsets carry the sidebar's LIST_RIGHT_GAP (4px) on
    // top of the base 8/36/64/92 spacing so the icons stay level with the note
    // list's right edge.
    right: "12px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    ...pressableButton,
  },
  sidebarNewGroupBtn: {
    position: "absolute",
    top: "16px",
    right: "96px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    ...pressableButton,
  },
  sidebarFilterBtn: {
    position: "absolute",
    top: "16px",
    right: "68px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    ...pressableButton,
  },
  sidebarSelectBtn: {
    position: "absolute",
    top: "16px",
    right: "40px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    ...pressableButton,
  },
  sidebarTopActionBtn: {
    opacity: 0,
    pointerEvents: "none",
    transitionProperty: "opacity, background-color, color, scale",
    transitionDuration: `${MOTION_DURATION_BASE}, ${MOTION_DURATION_FAST}, ${MOTION_DURATION_FAST}, ${MOTION_DURATION_FAST}`,
    transitionTimingFunction: "ease-out",
  },
  sidebarTopActionBtnVisible: {
    opacity: 1,
    pointerEvents: "auto",
    transitionDelay: `${MOTION_DURATION_BASE}, 0s, 0s, 0s`,
  },
  iconCrossfade: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "20px",
    height: "20px",
  },
  iconCrossfadeLayer: {
    position: "absolute",
    inset: 0,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    opacity: 0,
    scale: 0.25,
    filter: "blur(4px)",
    transitionProperty: "opacity, scale, filter",
    transitionDuration: MOTION_DURATION_MEDIUM,
    transitionTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
  },
  iconCrossfadeLayerVisible: {
    opacity: 1,
    scale: 1,
    filter: "blur(0px)",
  },
  floatingCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    flex: "1",
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopLeftRadius: "8px",
    overflow: "hidden",
    boxShadow: "-1px 0 3px rgba(0,0,0,0.08)",
    marginTop: "var(--shell-card-gap)",
  },
  content: {
    flex: "1",
    overflow: "auto",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
    position: "relative",
  },
  // Horizontal band above the status bar: editor scroll area + outline panel.
  editorRow: {
    display: "flex",
    flex: "1",
    minHeight: 0,
    minWidth: 0,
  },
  // Fixed-width outline slot (no resize handle, unlike the sidebar). The slot
  // animates width so the panel slides open/closed; visibility flips after the
  // collapse so hidden items leave the tab order and accessibility tree.
  outlineSlot: {
    width: "240px",
    flexShrink: 0,
    overflow: "hidden",
    visibility: "visible",
    transitionProperty: "width, visibility",
    transitionDuration: `${MOTION_DURATION_SLOW}, 0s`,
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
    transitionDelay: "0s, 0s",
    "@media screen and (prefers-reduced-motion: reduce)": {
      transitionDuration: "0.01ms, 0s",
    },
  },
  outlineSlotClosed: {
    width: "0px",
    visibility: "hidden",
    transitionDelay: `0s, ${MOTION_DURATION_SLOW}`,
    "@media screen and (prefers-reduced-motion: reduce)": {
      transitionDelay: "0s, 0s",
    },
  },
  // Transient F8 focus-mode notice: a small non-interactive pill floating
  // over the editor card. Dark translucent so it reads on both themes.
  focusNotice: {
    position: "absolute",
    bottom: "44px",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 30,
    padding: "6px 14px",
    borderRadius: "16px",
    backgroundColor: "rgba(0, 0, 0, 0.65)",
    color: "#fff",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    whiteSpace: "nowrap",
    pointerEvents: "none",
    userSelect: "none",
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: MOTION_DURATION_MEDIUM,
    transitionTimingFunction: "ease-out",
    "@media screen and (prefers-reduced-motion: reduce)": {
      transitionDuration: "0.01ms",
    },
  },
  focusNoticeVisible: {
    opacity: 1,
  },
  toolbarAnchor: {
    position: "sticky",
    top: 0,
    height: 0,
    zIndex: 10,
    overflow: "visible",
    pointerEvents: "none",
  },
  searchBarAnchor: {
    position: "sticky",
    top: 0,
    height: 0,
    zIndex: 50,
    overflow: "visible",
    pointerEvents: "none",
    opacity: 1,
    transform: "translateY(0)",
    filter: "blur(0px)",
    transitionProperty: "opacity, transform, filter",
    transitionDuration: MOTION_DURATION_FAST,
    transitionTimingFunction: "ease-in",
    animationName: {
      from: { opacity: 0, transform: "translateY(4px)", filter: "blur(4px)" },
      to: { opacity: 1, transform: "translateY(0)", filter: "blur(0px)" },
    },
    animationDuration: MOTION_DURATION_BASE,
    animationTimingFunction: "cubic-bezier(0.2, 0, 0, 1)",
    animationFillMode: "backwards",
  },
  searchBarAnchorExiting: {
    opacity: 0,
    transform: "translateY(-4px)",
    filter: "blur(4px)",
    pointerEvents: "none",
  },
  editorPane: {
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: MOTION_DURATION_BASE,
    transitionTimingFunction: "ease",
    height: "100%",
  },
  notesDirMergeButton: {
    justifyContent: "flex-start",
    backgroundColor: `${tokens.colorBrandBackground} !important`,
    color: `${tokens.colorNeutralForegroundOnBrand} !important`,
    ":hover, :focus-visible": {
      backgroundColor: `${tokens.colorBrandBackgroundHover} !important`,
      color: `${tokens.colorNeutralForegroundOnBrand} !important`,
    },
    ":hover:active": {
      backgroundColor: `${tokens.colorBrandBackgroundPressed} !important`,
      color: `${tokens.colorNeutralForegroundOnBrand} !important`,
    },
  },
});
