import { makeStyles, tokens } from "@fluentui/react-components";

export const useStyles = makeStyles({
  root: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    color: tokens.colorNeutralForeground1,
    position: "relative",
    transitionProperty: "filter",
    transitionDuration: "0.2s",
    transitionTimingFunction: "ease",
  },
  rootBlurred: {
    filter: "blur(4px)",
    willChange: "filter",
  },
  micaOverlay: {
    position: "absolute",
    inset: "0",
    pointerEvents: "none",
    zIndex: 1,
    opacity: 0,
    transitionProperty: "opacity",
    transitionDuration: "0.4s",
    transitionTimingFunction: "ease",
  },
  micaOverlayActive: {
    opacity: 1,
  },
  body: {
    flex: "1",
    display: "flex",
    position: "relative",
    overflow: "hidden",
    zIndex: 2,
  },
  sidebarSlot: {
    position: "relative",
    width: 0,
    flexShrink: 0,
    overflow: "hidden",
  },
  sidebarSlotAnimated: {
    transitionProperty: "width",
    transitionDuration: "0.3s",
    transitionTimingFunction: "cubic-bezier(0.4, 0, 0.2, 1)",
  },
  sidebarSlotOpen: {
    width: "var(--shell-sidebar-width)",
    overflow: "visible",
  },
  sidebarResizer: {
    position: "absolute",
    right: "-4px",
    top: 0,
    bottom: 0,
    width: "8px",
    cursor: "ew-resize",
    zIndex: 100,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    "::after": {
      content: '""',
      width: "4px",
      height: "56px",
      borderRadius: "4px",
      backgroundColor: tokens.colorBrandStroke1,
      opacity: 0,
      transitionProperty: "opacity",
      transitionDuration: "0.15s",
    },
    ":hover::after": {
      opacity: 1,
      transitionDelay: "0.3s",
    },
  },
  sidebarResizing: {
    cursor: "ew-resize",
    "::after": {
      opacity: "1 !important",
    },
  },
  sidebarToggle: {
    position: "absolute",
    top: "16px",
    left: "5px",
    zIndex: 10,
    display: "inline-flex",
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "8px",
    padding: "3px",
    pointerEvents: "none",
  },
  sidebarToggleBtn: {
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
    pointerEvents: "auto",
  },
  sidebarSearchBtn: {
    position: "absolute",
    top: "19px",
    right: "8px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
  },
  sidebarNewGroupBtn: {
    position: "absolute",
    top: "19px",
    right: "64px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
  },
  sidebarSelectBtn: {
    position: "absolute",
    top: "19px",
    right: "36px",
    zIndex: 10,
    borderRadius: "6px",
    border: "none",
    minWidth: "auto",
    height: "28px",
    width: "28px",
    padding: "0",
  },
  floatingCard: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    flex: "1",
    minWidth: 0,
    backgroundColor: tokens.colorNeutralBackground1,
    borderTopLeftRadius: "8px",
    overflow: "hidden",
    boxShadow: "-1px 0 3px rgba(0,0,0,0.08)",
    marginTop: "var(--shell-card-gap)",
  },
  content: {
    flex: "1",
    overflow: "auto",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
    position: "relative",
  },
  toolbarAnchor: {
    position: "sticky",
    top: 0,
    height: 0,
    zIndex: 10,
    overflow: "visible",
    pointerEvents: "none",
  },
  searchBarAnchor: {
    position: "sticky",
    top: 0,
    height: 0,
    zIndex: 50,
    overflow: "visible",
    pointerEvents: "none",
  },
  editorPane: {
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: "0.15s",
    transitionTimingFunction: "ease",
    height: "100%",
  },
  editorPaneHidden: {
    opacity: 0,
    position: "absolute",
    pointerEvents: "none",
    height: 0,
    overflow: "hidden",
  },
});
